/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
package org.apache.maven.report.projectinfo;

import javax.inject.Inject;

import java.io.IOException;
import java.io.InputStream;
import java.nio.file.Files;

import com.meterware.httpunit.HttpUnitOptions;
import org.apache.maven.artifact.DefaultArtifact;
import org.apache.maven.artifact.handler.manager.ArtifactHandlerManager;
import org.apache.maven.doxia.tools.SiteTool;
import org.apache.maven.model.io.xpp3.MavenXpp3Reader;
import org.apache.maven.project.MavenProject;
import org.codehaus.plexus.i18n.I18N;
import org.codehaus.plexus.util.xml.pull.XmlPullParserException;
import org.junit.jupiter.api.BeforeEach;

import static org.apache.maven.api.plugin.testing.MojoExtension.getTestFile;

/**
 * Abstract base class for testing project info reports.
 */
abstract class AbstractProjectInfoTest {

    @Inject
    protected MavenProject mavenProject;

    @Inject
    private ArtifactHandlerManager artifactHandlerManager;

    /**
     * The I18N plexus component.
     */
    @Inject
    private I18N i18n;

    @BeforeEach
    void setupHttpUnit() {
        HttpUnitOptions.setScriptingEnabled(false);
    }

    /**
     * Gets a fully qualified title as generated by Doxia Sitetools
     *
     * @param projectTitle the project title to prepare
     * @param shortTitle the short title to prepare
     * @return the prepared title as per Doxia Sitetools
     * @since 2.8
     */
    protected String prepareTitle(String projectTitle, String shortTitle) {
        if (projectTitle == null || projectTitle.isEmpty()) {
            throw new IllegalArgumentException("The name cannot be empty");
        }

        if (shortTitle == null || shortTitle.isEmpty()) {
            throw new IllegalArgumentException("The title cannot be empty");
        }

        return String.format("%s \u2013 %s", shortTitle, projectTitle);
    }

    /**
     * Gets a trimmed String for the given key from the resource bundle defined by Plexus.
     *
     * @param key the key for the desired string
     * @return the string for the given key
     */
    protected String getString(String key) {
        if (key == null || key.isEmpty()) {
            throw new IllegalArgumentException("The key cannot be empty");
        }

        return i18n.getString("project-info-reports", SiteTool.DEFAULT_LOCALE, key)
                .trim();
    }

    protected void readMavenProjectModel(MavenProject project, String pom) throws IOException {
        MavenXpp3Reader pomReader = new MavenXpp3Reader();
        try (InputStream in = Files.newInputStream(getTestFile(pom).toPath())) {
            project.setModel(pomReader.read(in));
        } catch (XmlPullParserException e) {
            throw new IOException(e);
        }
    }

    protected void setArtifactForProject(MavenProject project) {
        project.setArtifact(new DefaultArtifact(
                project.getGroupId(),
                project.getArtifactId(),
                project.getVersion(),
                null,
                project.getPackaging(),
                null,
                artifactHandlerManager.getArtifactHandler(project.getPackaging())));
    }
}
